### ISSUE TITLE
Import error when using example (python 3.3.0 - win 10)

### ISSUE THREAD

**Issue by thepizzagui** [awkman/pywifi#10]
Occurs when trying to import native_wifi from wifiutils. This is done by using the example provided.  

``` Python
Traceback (most recent call last):
  File "C:/Users/goose/PycharmProjects/wifiSwap/main.py", line 1, in <module>
    import pywifi
  File "C:\Python33\lib\site-packages\pywifi\__init__.py", line 3, in <module>
    from .pywifi import *
  File "C:\Python33\lib\site-packages\pywifi\pywifi.py", line 5, in <module>
    from .iface import Interface
  File "C:\Python33\lib\site-packages\pywifi\iface.py", line 7, in <module>
    from .win import wifiutils
  File "C:\Python33\lib\site-packages\pywifi\win\wifiutils.py", line 6, in <module>
    from . import native_wifi as wifiapi
ImportError: cannot import name native_wifi
```

Not sure if there is an issue with the package or my current setup (using latest version of pycharm). Doesn't seem to have a circular import.

**Comment by awkman** [comment]
Now pywifi moves to v1.0.0, please try it.

**Comment by thepizzagui** [comment]
breaks at wifiutils: 

```Python
Traceback (most recent call last):
  File "C:/Users/goose/PycharmProjects/wifiSwap/main.py", line 1, in <module>
    import pywifi
  File "C:\Python33\lib\site-packages\pywifi\__init__.py", line 14, in <module>
    from .wifi import PyWiFi
  File "C:\Python33\lib\site-packages\pywifi\wifi.py", line 15, in <module>
    from .iface import Interface
  File "C:\Python33\lib\site-packages\pywifi\iface.py", line 11, in <module>
    from .win import wifiutil
ImportError: cannot import name wifiutil
```
Just to confirm, is this an issue with the package?

**Comment by awkman** [comment]
I tested under 3.5.2 env and it work fine. But testing under python3.3.5 env. I found the it failed:
`Python 3.3.5 (v3.3.5:62cf4e77f785, Mar  9 2014, 10:35:05) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pywifi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python33\lib\site-packages\pywifi\__init__.py", line 14, in <module>
    from .wifi import PyWiFi
  File "C:\Python33\lib\site-packages\pywifi\wifi.py", line 15, in <module>
    from .iface import Interface
  File "C:\Python33\lib\site-packages\pywifi\iface.py", line 11, in <module>
    from .win import wifiutil
  File "C:\Python33\lib\site-packages\pywifi\win\wifiutil.py", line 10, in <module>
    from enum import Enum
ImportError: No module named 'enum'`

Maybe you can try it under python3.4+

**Comment by chibill** [comment]
Maybe install enum? (It is in pypi)

**Comment by thepizzagui** [comment]
I'll try this later on today, Might be a good idea to show the interpreter requirement in the readme.

**Comment by awkman** [comment]
Yes, you are right. I found the 'from enum import Enum' can be removed because now pywifi doesn't need it anymore. After that, pywif can work properly in py3.3 env.
I will update both of the readme and code recently.

**Comment by awkman** [comment]
@thepizzagui  After changing the test env to py3.3.0, I saw the same issue as you reported. It seems there are some changes between 3.3.0 and 3.3.5. I think this issue will not be fixed recently because I want to replace the d-bus communication between pywifi and wpa_supplicant with sockets.

**Comment by thepizzagui** [comment]
Upgrading seems to do the trick, looks like we'll never know!

**Comment by edgedroper** [comment]
import pywifi error!
my python env is 3.6.3
>>> import pywifi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pywifi/__init__.py", line 15, in <module>
    from .wifi import PyWiFi
  File "/usr/local/lib/python3.6/site-packages/pywifi/wifi.py", line 15, in <module>
    from .iface import Interface
  File "/usr/local/lib/python3.6/site-packages/pywifi/iface.py", line 15, in <module>
    raise NotImplementedError
NotImplementedError
>>>

this version don't support pywifi?

**Comment by wgaylord** [comment]
What operating system?

**Comment by edgedroper** [comment]
mac OS

**Comment by edgedroper** [comment]
mac OS  10.13.1

**Comment by wgaylord** [comment]
If you look at the readme you will see that Mac is not currently supported.

**Comment by edgedroper** [comment]
OK,Thank you wgaylord , i will use it at linux!

**Comment by wgaylord** [comment]
Your welcome
