### ISSUE TITLE
Cannot import pywifi

### ISSUE THREAD

**Issue by Aaron2412** [awkman/pywifi#28]
Python 2.7.10 (default, Oct  6 2017, 22:29:07)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pywifi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pywifi/__init__.py", line 15, in <module>
    from .wifi import PyWiFi
  File "pywifi/wifi.py", line 15, in <module>
    from .iface import Interface
  File "pywifi/iface.py", line 15, in <module>
    raise NotImplementedError
NotImplementedError

pip showed that pywifi is installed correctly

**Comment by Aaron2412** [comment]
Fixed

**Comment by HaddyYang** [comment]
@Aaron2412 how do you fix it?
