### ISSUE TITLE
Cannot scan on linux

### ISSUE THREAD

**Issue by kootenpv** [awkman/pywifi#4]
Perhaps I'm missing something, but the following doesn't work:

```python
>>> import pywifi
>>> iface = pywifi.PyWiFi().interfaces()[0]
>>> iface.scan()
>>> iface.scan_results()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/pywifi/iface.py", line 39, in scan_results
    return wifiutils.scan_results(self.__raw_obj)
  File "/usr/lib/python3.5/site-packages/pywifi/linux/wifiutils.py", line 48, in scan_results
    security += tmp_rsn['KeyMgmt']
TypeError: unsupported operand type(s) for +=: 'bool' and 'dbus.Array'
```
@awkman any idea?

**Comment by Michael-Jalloh** [comment]
Yes it doesn't. I just tried it too. Can u please help

**Comment by awkman** [comment]
I pull a new commit to fix this issue, please try it again.

**Comment by kootenpv** [comment]
Fixed!
